name: 'ci-cd pipeline'

on:
    push:
        branches:
            - main
            - main

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: 'npm'
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm install

            - name: Build file
              run: npm run build --verbose

            - name: Deploy production to Netlify
              uses: South-Paw/action-netlify-deploy@v1.2.0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
                  build-dir: '.next'
                  comment-on-commit: true
